/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * lithos `Speed`: the requested latency or cost tier.
 */

export const BillingSpeed = {
    FAST: 'fast',
    BALANCED: 'balanced',
    ECONOMICAL: 'economical'
} as const;

export type BillingSpeed = typeof BillingSpeed[keyof typeof BillingSpeed];
