/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A lithos `ToolChoice`, discriminated by `type`.
 */
export interface CompletionToolChoice {
    /**
     * Tool selection mode.
     */
    'type': CompletionToolChoiceTypeEnum;
    /**
     * Required when type is `tool`.
     */
    'name'?: string;
}

export const CompletionToolChoiceTypeEnum = {
    AUTO: 'auto',
    NONE: 'none',
    REQUIRED: 'required',
    TOOL: 'tool'
} as const;

export type CompletionToolChoiceTypeEnum = typeof CompletionToolChoiceTypeEnum[keyof typeof CompletionToolChoiceTypeEnum];
