/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * lithos `ResponseFormat`, discriminated by `type`: `text`, `json_object`, or `json_schema` ({name, schema}).
 */
export interface CompletionResponseFormat {
    [key: string]: any;

    'type': CompletionResponseFormatTypeEnum;
}

export const CompletionResponseFormatTypeEnum = {
    TEXT: 'text',
    JSON_OBJECT: 'json_object',
    JSON_SCHEMA: 'json_schema'
} as const;

export type CompletionResponseFormatTypeEnum = typeof CompletionResponseFormatTypeEnum[keyof typeof CompletionResponseFormatTypeEnum];
