/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompletionContentPart } from './completion-content-part';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionCost } from './completion-cost';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionResponseWarningsInner } from './completion-response-warnings-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionUsage } from './completion-usage';
// May contain unused imports in some cases
// @ts-ignore
import type { ModelHandle } from './model-handle';

/**
 * A lithos `Response`, returned verbatim. The server is the billing authority: `cost` is the catalog estimate or the provider\'s own figure. When the request carried `schema`, `output` holds the parsed object.
 */
export interface CompletionResponse {
    'output'?: any;
    'id'?: string | null;
    'model': ModelHandle;
    'content': Array<CompletionContentPart>;
    /**
     * Tool calls withheld because the turn ended early.
     */
    'suppressed_tool_calls'?: Array<{ [key: string]: any; }>;
    /**
     * Why generation stopped: stop, length, tool_call, content_filter, error, incomplete, or a provider-specific reason.
     */
    'finish_reason': string;
    'usage': CompletionUsage;
    'cost'?: CompletionCost;
    'rate_limits'?: { [key: string]: any; };
    'warnings'?: Array<CompletionResponseWarningsInner>;
    'raw'?: any;
}
