/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CompletionToolDefinitionKind } from './completion-tool-definition-kind';

/**
 * A lithos `ToolDefinition`. `kind` is `{type: function, input_schema}` for JSON-argument tools or `{type: custom, format}` for free-form input.
 */
export interface CompletionToolDefinition {
    /**
     * Tool name.
     */
    'name': string;
    /**
     * Human-readable tool description.
     */
    'description': string;
    'kind': CompletionToolDefinitionKind;
}
