/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * lithos `TokenCounts`: five disjoint token buckets for one completion. `input` excludes cache reads and writes, while `output` excludes reasoning tokens when the provider reports them separately.
 */
export interface CompletionUsage {
    /**
     * Uncached prompt tokens.
     */
    'input'?: number;
    /**
     * Non-reasoning completion tokens.
     */
    'output'?: number;
    /**
     * Separately reported reasoning tokens.
     */
    'reasoning'?: number;
    /**
     * Prompt tokens served from a provider cache.
     */
    'cache_read'?: number;
    /**
     * Prompt tokens written to a provider cache.
     */
    'cache_write'?: number;
}
