/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingSpeed } from './billing-speed';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionMessage } from './completion-message';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionResponseFormat } from './completion-response-format';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionToolChoice } from './completion-tool-choice';
// May contain unused imports in some cases
// @ts-ignore
import type { CompletionToolDefinition } from './completion-tool-definition';
// May contain unused imports in some cases
// @ts-ignore
import type { ReasoningEffort } from './reasoning-effort';

/**
 * A lithos `Request` plus `stream`. Field names match the lithos wire form so a serialized lithos request can be posted as-is.
 */
export interface CreateCompletionRequest {
    /**
     * The conversation messages.
     */
    'messages': Array<CompletionMessage>;
    /**
     * Model selector: `provider/model`, a model id or alias, or a provider id. The server picks a ready-provider default when omitted.
     */
    'model'?: string;
    /**
     * Optional provider pin for a bare model selector.
     */
    'provider'?: string;
    /**
     * System prompt (convenience; prepended as a system message).
     */
    'system'?: string;
    /**
     * Stream response via SSE.
     */
    'stream'?: boolean;
    /**
     * Tool definitions available to the model.
     */
    'tools'?: Array<CompletionToolDefinition>;
    'tool_choice'?: CompletionToolChoice;
    'response_format'?: CompletionResponseFormat;
    'schema'?: any;
    'max_output_tokens'?: number;
    'temperature'?: number;
    'top_p'?: number;
    /**
     * Stop sequences.
     */
    'stop_sequences'?: Array<string>;
    /**
     * Reasoning effort level.
     */
    'reasoning_effort'?: ReasoningEffort;
    /**
     * Requested speed tier.
     */
    'speed'?: BillingSpeed;
    /**
     * Request tags forwarded to providers that accept them.
     */
    'metadata'?: { [key: string]: string; };
    /**
     * Raw provider options keyed by provider id.
     */
    'provider_options'?: { [key: string]: any; };
}
