/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Desired environment provider.
 */

export const EnvironmentProvider = {
    LOCAL: 'local',
    DOCKER: 'docker',
    DAYTONA: 'daytona',
    KUBERNETES: 'kubernetes'
} as const;

export type EnvironmentProvider = typeof EnvironmentProvider[keyof typeof EnvironmentProvider];
