/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A single self-hosted Forgejo instance. The access token lives in the secret vault (`FORGEJO_TOKEN`), never in settings.
 */
export interface ForgejoIntegrationSettings {
    'enabled': boolean;
    /**
     * Forgejo instance base URL (HTTPS, optional subpath).
     */
    'url': string | null;
}
