/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ScmProvider } from './scm-provider';

/**
 * Repository target. The branch names the attached working branch. An optional tag selects a release at worker start, and an optional exact SHA is authoritative when both are present. The provider names the forge hosting the repository; it defaults to `github`, and `forgejo` targets resolve against the configured Forgejo instance.
 */
export interface GitRunTarget {
    'kind': GitRunTargetKindEnum;
    /**
     * Repository slug in `owner/name` form.
     */
    'repo': string;
    /**
     * Required attached working branch name, preserved exactly.
     */
    'branch': string;
    /**
     * Optional bare tag name. Prefixes such as `refs/tags/` and `tags/` are rejected. Without `sha`, the worker resolves this tag when the sandbox starts and fails if it is unavailable.
     */
    'tag'?: string;
    /**
     * Optional exact commit. The server lowercase-normalizes its syntax but does not resolve it, prove branch ancestry, or prove that it matches an accompanying tag. When present, this exact commit wins.
     */
    'sha'?: string;
    'provider'?: ScmProvider;
}

export const GitRunTargetKindEnum = {
    GIT: 'git'
} as const;

export type GitRunTargetKindEnum = typeof GitRunTargetKindEnum[keyof typeof GitRunTargetKindEnum];
