/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Forgejo instance URL and personal access token chosen during browser install.
 */
export interface InstallForgejoTokenInput {
    /**
     * Forgejo instance base URL (HTTPS).
     */
    'url': string;
    'token': string;
}
