/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request body for linking an existing GitHub or Forgejo/Gitea pull request to a run.
 */
export interface LinkRunPullRequestRequest {
    /**
     * Pull request URL to associate with the run. GitHub URLs must use `https://github.com/{owner}/{repo}/pull/{number}`; Forgejo/Gitea URLs must use `{instance}/{owner}/{repo}/pulls/{number}` on the configured instance.
     */
    'html_url': string;
}
