/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Capability flags for a model, from the lithos catalog.
 */
export interface ModelFeatures {
    /**
     * Whether the model supports tool use.
     */
    'tools': boolean;
    /**
     * Whether the model supports image inputs.
     */
    'vision': boolean;
    /**
     * Whether the model supports extended reasoning.
     */
    'reasoning': boolean;
    /**
     * Whether the model endpoint supports prompt caching.
     */
    'prompt_cache': boolean;
    /**
     * Whether the model accepts classic sampling parameters (temperature, top_p).
     */
    'sampling': boolean;
}
