/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Minimal pull request link associated with a run. GitHub links are the default; a `forge` base URL marks a pull request on a self-hosted Forgejo instance.
 */
export interface PullRequestLink {
    'owner': string;
    'repo': string;
    'number': number;
    /**
     * Computed web URL for the pull request.
     */
    'html_url': string;
    /**
     * Instance base URL when the pull request lives on a configured Forgejo instance; omitted for GitHub.
     */
    'forge'?: string;
}
