/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Present only for pull requests on a Forgejo instance.
 */
export interface PullRequestLinkForge {
    /**
     * Base URL of the self-hosted Forgejo instance.
     */
    'base_url': string;
}
