/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PullRequestLinkForge } from './pull-request-link-forge';

/**
 * Minimal pull request link associated with a run. GitHub links carry only `owner`/`repo`/`number`; links on a Forgejo instance also carry a `forge` object with the instance base URL.
 */
export interface PullRequestLink {
    'owner': string;
    'repo': string;
    'number': number;
    /**
     * Computed web URL for the pull request. GitHub links use `https://github.com/{owner}/{repo}/pull/{number}`; Forgejo links use `{forge.base_url}/{owner}/{repo}/pulls/{number}`.
     */
    'html_url': string;
    'forge'?: PullRequestLinkForge;
}
