/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Minimal pull request link associated with a run.
 */
export interface PullRequestLink {
    'owner': string;
    'repo': string;
    'number': number;
    /**
     * Computed web URL for the pull request.
     */
    'html_url': string;
    /**
     * Base URL of the Forgejo/Gitea instance when the pull request lives on a self-hosted instance; absent for github.com.
     */
    'instance_url'?: string;
}
