/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Durable repository metadata for a run.
 */
export interface RepositoryRef {
    'name': string;
    'origin_url': string | null;
    'provider': RepositoryRefProviderEnum;
}

export const RepositoryRefProviderEnum = {
    GITHUB: 'github',
    FORGEJO: 'forgejo',
    GIT: 'git',
    UNKNOWN: 'unknown'
} as const;

export type RepositoryRefProviderEnum = typeof RepositoryRefProviderEnum[keyof typeof RepositoryRefProviderEnum];
