/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Whether the run receives the configured Forgejo instance token as `FORGEJO_TOKEN`. Forgejo PAT scopes are fixed at token creation, so there is no permission map.
 */
export interface RunIntegrationsForgejoSettings {
    /**
     * Expose `FORGEJO_TOKEN` in the sandbox environment. Omitted when false so settings serialized by this release stay byte-identical to earlier releases for runs without the flag.
     */
    'token'?: boolean;
}
