/* tslint:disable */
/* eslint-disable */
/**
 * Fabro Run API
 * HTTP API for managing Fabro workflow run executions.
 *
 * The version of the OpenAPI document: 0.2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FolderRunTarget } from './folder-run-target';
// May contain unused imports in some cases
// @ts-ignore
import type { GitRunTarget } from './git-run-target';
// May contain unused imports in some cases
// @ts-ignore
import type { NoneRunTarget } from './none-run-target';
// May contain unused imports in some cases
// @ts-ignore
import type { ScmProvider } from './scm-provider';

/**
 * @type RunTarget
 * Workspace content and location requested for a run.
 */
export type RunTarget = { kind: 'folder' } & FolderRunTarget | { kind: 'git' } & GitRunTarget | { kind: 'none' } & NoneRunTarget;
